{
 "title": "Url_Shortener_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "APP Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Latency per Route Every 5 m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "seconds (s)" } },
   "targets": [
    {
     "expr": "sum by (route)(\r\n  rate(http_request_duration_seconds_sum[5m])\r\n)\r\n/\r\nsum by (route)(\r\n  rate(http_request_duration_seconds_count[5m])\r\n)\r\n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total 404 Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(url_shortener_404_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Shortened URLs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(url_shortener_shortened_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Redirects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(url_shortener_redirects_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Containers  Metrics Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Containers CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\r\n  rate(\r\n    container_cpu_usage_seconds_total{\r\n      job=\"c-advisor\",\r\n      container_label_com_docker_compose_service=~\"backend|frontend|mongo\"\r\n    }[5m]\r\n  )\r\n)\r\n",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Containers Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service)(\r\n  container_fs_usage_bytes{\r\n    job=\"c-advisor\",\r\n    container_label_com_docker_compose_service=~\"backend|frontend|mongo\"\r\n  }\r\n) / 1024 / 1024\r\n",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Containers Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\r\n  container_memory_usage_bytes{\r\n    job=\"c-advisor\",\r\n    container_label_com_docker_compose_service=~\"backend|frontend|mongo\"\r\n  }\r\n) / 1024 / 1024\r\n",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Containers Network Outbound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service)(\r\n  rate(container_network_transmit_bytes_total{\r\n    job=\"c-advisor\",\r\n    container_label_com_docker_compose_service=~\"backend|frontend|mongo\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Containers Network Inbound",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service)(\r\n  rate(container_network_receive_bytes_total{\r\n    job=\"c-advisor\",\r\n    container_label_com_docker_compose_service=~\"backend|frontend|mongo\"\r\n  }[5m])\r\n)\r\n",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  { "title": "Host Metrics Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Host CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (\r\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n)) * 100\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "max by (instance) (\r\n  100 *\r\n  (1 -\r\n    node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}\r\n    /\r\n    node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}\r\n  )\r\n)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum by (instance)(\r\n  (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100\r\n)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Network Outbound",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "targets": [
    {
     "expr": "sum by (instance)(\r\n  rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m])\r\n)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Network Inbound",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "targets": [
    {
     "expr": "sum by (instance)(\r\n  rate(node_network_receive_bytes_total{device!~\"lo\"}[5m])\r\n)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}